// src/app/OutputPanel.jsx
import { PauseCircleIcon } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import {
  buildRevenueSummary,
  formatElapsed,
  formatPlainNumber,
  formatPlayCountDisplay,
  formatPlayCountWanFixed,
  formatRevenue,
  formatRevenueRange,
  formatRewardValue,
} from "@/app/app-utils";

function SectionCard({ title, children }) {
  return (
    <Card className="bg-[rgba(255,252,247,0.98)] shadow-[0_22px_50px_-40px_rgba(30,32,41,0.14)]">
      <CardHeader className="border-b border-border/75 bg-muted/30 pb-4">
        <CardTitle className="text-base sm:text-lg">{title}</CardTitle>
      </CardHeader>
      <CardContent className="pt-5">{children}</CardContent>
    </Card>
  );
}

function MetricPair({ label, value }) {
  return (
    <div className="rounded-[calc(var(--radius)-0.12rem)] border border-[rgba(30,32,41,0.08)] bg-[rgba(255,252,247,0.92)] px-3.5 py-3">
      <div className="text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">{label}</div>
      <div className="mt-2 min-w-0 whitespace-nowrap text-base font-semibold leading-none tracking-tight sm:text-lg lg:text-xl">
        {value}
      </div>
    </div>
  );
}

export function OutputPanel({
  platform,
  progress,
  currentAction,
  elapsedMs,
  playCountResults,
  playCountSelectedEpisodeCount,
  playCountTotal,
  playCountFailed,
  idResults,
  suspectedOverflowEpisodes = [],
  idSelectedEpisodeCount,
  totalDanmaku,
  totalUsers,
  revenueResults,
  revenueSummary,
  isRunning,
  onCancelStatistics,
}) {
  const resolvedRevenueSummary = revenueSummary || buildRevenueSummary(revenueResults, platform);

  function getPaidCountLabel(drama) {
    if (drama?.platform === "manbo" && drama?.paidCountSource === "pay_count") {
      return "付费人数";
    }
    return "付费用户 ID 数";
  }

  function getSummaryPaidCountLabel(summary) {
    if (summary?.platform === "manbo" && summary?.paidCountSourceSummary === "pay_count") {
      return "总付费人次";
    }
    return "总和去重 ID";
  }

  function getRewardLabel(drama, isSummary = false) {
    if (drama?.platform === "manbo") {
      return "投喂总数";
    }
    return isSummary ? "打赏榜总和（钻石）" : "打赏榜累计（钻石）";
  }

  function formatRewardMetricValue(drama) {
    if (drama?.platform === "manbo") {
      return formatRewardValue(drama.platform, drama.diamondValue);
    }
    return formatPlainNumber(drama?.rewardCoinTotal);
  }

  function hasRewardNum(drama) {
    return drama?.platform === "missevan" && drama?.rewardNum != null && Number.isFinite(Number(drama?.rewardNum));
  }

  function shouldShowRevenueRange(drama) {
    if (!drama || drama.failed) {
      return false;
    }
    if (drama.minRevenueYuan == null || drama.maxRevenueYuan == null) {
      return false;
    }
    return Number.isFinite(Number(drama.minRevenueYuan)) && Number.isFinite(Number(drama.maxRevenueYuan));
  }

  function getRevenueLabel(drama) {
    return drama?.vipOnlyReward ? "预估收益（仅计算打赏）" : "预估收益";
  }

  const hasAnyResults = Boolean(
    playCountResults?.length || idResults?.length || revenueResults?.length
  );

  if (!isRunning && !hasAnyResults) {
    return null;
  }

  return (
    <div className="grid gap-4">
      <Card className="bg-[linear-gradient(180deg,rgba(43,46,92,0.98),rgba(59,62,122,0.96))] text-white shadow-[0_24px_52px_-40px_rgba(59,62,122,0.4)]">
        <CardContent className="flex flex-col gap-5 p-6">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
            <div className="space-y-2">
              <div className="text-xs font-semibold uppercase tracking-[0.22em] text-white/70">
                运行状态
              </div>
              <div className="text-xl font-semibold">{currentAction || "等待执行操作"}</div>
              <div className="flex flex-wrap items-center justify-between gap-2 text-sm text-white/78">
                <div>处理用时：{formatElapsed(elapsedMs)}</div>
                <div className="flex flex-wrap items-center justify-end gap-2">
                  {isRunning ? (
                    <Badge className="border-white/18 bg-white/16 px-3 py-1 text-white">进行中</Badge>
                  ) : (
                    <Badge variant="secondary" className="border border-white/16 bg-[rgba(255,240,233,0.92)] px-3 py-1 text-[rgb(126,75,67)]">空闲</Badge>
                  )}
                  {isRunning ? (
                    <Button variant="secondary" size="sm" onClick={onCancelStatistics}>
                      <PauseCircleIcon data-icon="inline-start" />
                      取消
                    </Button>
                  ) : null}
                </div>
              </div>
            </div>
            <div className="text-2xl font-semibold sm:pt-8">{progress}%</div>
          </div>
          <Progress value={progress} className="h-2.5 rounded-full bg-white/18" indicatorClassName="bg-[rgba(255,245,236,0.96)]" />
        </CardContent>
      </Card>

      {playCountResults?.length ? (
        <SectionCard title="播放量统计">
          <div className="grid gap-3 sm:grid-cols-2">
            {playCountResults.map((drama) => (
              <div key={`play-${drama.title}`} className="rounded-[calc(var(--radius)+0.05rem)] border border-[rgba(30,32,41,0.08)] bg-[rgba(255,252,247,0.94)] p-4">
                <div className="text-sm font-medium text-muted-foreground">{drama.title} / 已选 {drama.selectedEpisodeCount} 集</div>
                <div className="mt-3 text-3xl font-semibold">{formatPlayCountDisplay(drama.playCountTotal, drama.playCountFailed)}</div>
              </div>
            ))}
            <div className="rounded-[calc(var(--radius)+0.05rem)] border border-[rgba(59,62,122,0.18)] bg-[rgba(59,62,122,0.94)] p-4 text-white">
              <div className="text-sm font-medium text-white/76">汇总 / 已选 {playCountSelectedEpisodeCount} 集</div>
              <div className="mt-3 text-3xl font-semibold">{formatPlayCountDisplay(playCountTotal, playCountFailed)}</div>
            </div>
          </div>
        </SectionCard>
      ) : null}

      {idResults?.length ? (
        <SectionCard title="弹幕与去重 ID 统计">
          <div className="grid gap-3 sm:grid-cols-2">
            {idResults.map((drama) => (
              <div key={`id-${drama.title}`} className="rounded-[calc(var(--radius)+0.05rem)] border border-[rgba(30,32,41,0.08)] bg-[rgba(255,252,247,0.94)] p-4">
                <div className="text-sm font-medium text-muted-foreground">{drama.title} / 已选 {drama.selectedEpisodeCount} 集</div>
                <div className="mt-4 grid grid-cols-2 gap-3">
                  <MetricPair label="总弹幕数" value={formatPlainNumber(drama.danmaku)} />
                  <MetricPair label="去重 ID 数" value={formatPlainNumber(drama.users)} />
                </div>
              </div>
            ))}
            <div className="rounded-[calc(var(--radius)+0.05rem)] border border-[rgba(239,131,95,0.22)] bg-[rgba(255,240,233,0.9)] p-4 sm:col-span-2">
              <div className="text-sm font-medium text-muted-foreground">汇总 / 已选 {idSelectedEpisodeCount} 集</div>
              <div className="mt-4 grid grid-cols-2 gap-3">
                <MetricPair label="总弹幕数" value={formatPlainNumber(totalDanmaku)} />
                <MetricPair label="去重 ID 数" value={formatPlainNumber(totalUsers)} />
              </div>
              {suspectedOverflowEpisodes?.length ? (
                <div className="mt-4 grid gap-2 rounded-[calc(var(--radius)-0.08rem)] border border-dashed border-[rgba(239,131,95,0.26)] bg-[rgba(255,252,247,0.94)] p-3">
                  <div className="text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">
                    疑似弹幕溢出分集
                  </div>
                  {suspectedOverflowEpisodes.map((title) => (
                    <div key={`overflow-${title}`} className="text-sm">
                      {title}
                    </div>
                  ))}
                </div>
              ) : null}
            </div>
          </div>
        </SectionCard>
      ) : null}

      {revenueResults?.length ? (
        <SectionCard title="最低收益预估">
          <div className="grid gap-3 sm:grid-cols-2">
            {revenueResults.map((drama) => (
              <div key={`revenue-${drama.dramaId}`} className="rounded-[calc(var(--radius)+0.05rem)] border border-[rgba(30,32,41,0.08)] bg-[rgba(255,252,247,0.94)] p-4">
                <div className="text-sm font-medium text-muted-foreground">
                  {drama.subtitle || `${drama.title} / 单价 ${drama.price || 0} 钻石`}
                </div>
                <div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-3">
                  <MetricPair label={getPaidCountLabel(drama)} value={drama.failed ? "访问失败" : formatPlainNumber(drama.paidUserCount)} />
                  <MetricPair
                    label={getRewardLabel(drama)}
                    value={drama.failed ? "访问失败" : formatRewardMetricValue(drama)}
                  />
                  {hasRewardNum(drama) ? <MetricPair label="打赏人数" value={formatPlainNumber(drama.rewardNum)} /> : null}
                </div>
                <div className="mt-4 rounded-[calc(var(--radius)-0.08rem)] border border-[rgba(59,62,122,0.18)] bg-[rgba(59,62,122,0.92)] p-4 text-white">
                  <div className="text-xs font-semibold uppercase tracking-[0.2em] text-white/72">{getRevenueLabel(drama)}</div>
                  <div className="mt-2 text-2xl font-semibold">
                    {drama.failed
                      ? "预估失败"
                      : shouldShowRevenueRange(drama)
                        ? formatRevenueRange(drama.minRevenueYuan, drama.maxRevenueYuan)
                        : formatRevenue(drama.estimatedRevenueYuan)}
                  </div>
                </div>
              </div>
            ))}

            {resolvedRevenueSummary ? (
              <div className="rounded-[calc(var(--radius)+0.05rem)] border border-[rgba(239,131,95,0.18)] bg-[rgba(255,248,243,0.95)] p-4 sm:col-span-2">
                <div className="text-sm font-medium text-muted-foreground">
                  {resolvedRevenueSummary.summaryTitle || `汇总 / 已选 ${resolvedRevenueSummary.selectedDramaCount} 部`}
                </div>
                <div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4">
                  {resolvedRevenueSummary.paidCountSourceSummary === "mixed" ? (
                    <>
                      <MetricPair label="总付费人次" value={resolvedRevenueSummary.failed ? "访问失败" : formatPlainNumber(resolvedRevenueSummary.totalPayCount)} />
                      <MetricPair label="总和去重 ID" value={resolvedRevenueSummary.failed ? "访问失败" : formatPlainNumber(resolvedRevenueSummary.totalDanmakuPaidUserCount)} />
                    </>
                  ) : (
                    <MetricPair
                      label={getSummaryPaidCountLabel(resolvedRevenueSummary)}
                      value={resolvedRevenueSummary.failed ? "访问失败" : formatPlainNumber(resolvedRevenueSummary.totalPaidUserCount)}
                    />
                  )}
                  <MetricPair label="总播放量" value={resolvedRevenueSummary.failed ? "访问失败" : formatPlayCountWanFixed(resolvedRevenueSummary.totalViewCount)} />
                  <MetricPair
                    label={getRewardLabel(resolvedRevenueSummary, true)}
                    value={resolvedRevenueSummary.failed ? "访问失败" : resolvedRevenueSummary.platform === "manbo" ? formatRewardValue(resolvedRevenueSummary.platform, resolvedRevenueSummary.rewardTotal) : formatPlainNumber(resolvedRevenueSummary.rewardTotal)}
                  />
                  {hasRewardNum(resolvedRevenueSummary) ? <MetricPair label="打赏人次" value={formatPlainNumber(resolvedRevenueSummary.rewardNum)} /> : null}
                </div>
                <div className="mt-4 rounded-[calc(var(--radius)-0.08rem)] border border-[rgba(59,62,122,0.18)] bg-[rgba(59,62,122,0.92)] p-4 text-white">
                  <div className="text-xs font-semibold uppercase tracking-[0.2em] text-white/72">收益预估</div>
                  <div className="mt-2 text-2xl font-semibold">
                    {resolvedRevenueSummary.failed
                      ? "预估失败"
                      : shouldShowRevenueRange(resolvedRevenueSummary)
                        ? formatRevenueRange(resolvedRevenueSummary.minRevenueYuan, resolvedRevenueSummary.maxRevenueYuan)
                        : formatRevenue(resolvedRevenueSummary.estimatedRevenueYuan)}
                  </div>
                </div>
              </div>
            ) : null}
          </div>
        </SectionCard>
      ) : null}
    </div>
  );
}

// src/components/OutputPanel.vue
<template>
  <div class="output-panel">
    <div class="output-status-card">
      <div class="status-header">
        <div>
          <div class="status-kicker">运行状态</div>
          <div class="status-text">{{ currentAction || "等待执行操作" }}</div>
          <div class="status-elapsed">处理用时：{{ formatElapsed(elapsedMs) }}</div>
        </div>
        <div class="status-side">
          <div v-if="isRunning" class="status-badge">进行中</div>
          <button
            v-if="isRunning"
            type="button"
            class="status-cancel-btn"
            @click="$emit('cancelStatistics')"
          >
            取消
          </button>
          <div class="status-progress">{{ progress }}%</div>
        </div>
      </div>

      <div class="output-progress">
        <div class="output-progress-bar" :style="{ width: `${progress}%` }"></div>
      </div>
    </div>

    <div v-if="playCountResults.length" class="output-section">
      <div class="output-section-title">播放量统计</div>
      <div class="output-list">
        <div
          v-for="drama in playCountResults"
          :key="`play-${drama.title}`"
          class="output-card"
        >
          <div class="output-card-title">
            {{ drama.title }} / 已选 {{ drama.selectedEpisodeCount }} 集
          </div>
          <div class="output-stat-label">总播放量</div>
          <div class="output-stat-value">
            {{ formatPlayCountDisplay(drama.playCountTotal, drama.playCountFailed) }}
          </div>
        </div>

        <div class="output-summary-card">
          <div class="output-card-title">汇总 / 已选 {{ playCountSelectedEpisodeCount }} 集</div>
          <div class="output-stat-label">总播放量</div>
          <div class="output-stat-value">
            {{ formatPlayCountDisplay(playCountTotal, playCountFailed) }}
          </div>
        </div>
      </div>
    </div>

    <div v-if="idResults.length" class="output-section">
      <div class="output-section-title">弹幕与去重 ID 统计</div>
      <div class="output-list">
        <div
          v-for="drama in idResults"
          :key="`id-${drama.title}`"
          class="output-card"
        >
          <div class="output-card-title">
            {{ drama.title }} / 已选 {{ drama.selectedEpisodeCount }} 集
          </div>
          <div class="output-stats">
            <div>
              <div class="output-stat-label">总弹幕数</div>
              <div class="output-stat-value">{{ drama.danmaku }}</div>
            </div>
            <div>
              <div class="output-stat-label">去重 ID 数</div>
              <div class="output-stat-value">{{ drama.users }}</div>
            </div>
          </div>
        </div>

        <div class="output-summary-card">
          <div class="output-card-title">汇总 / 已选 {{ idSelectedEpisodeCount }} 集</div>
          <div class="output-stats">
            <div>
              <div class="output-stat-label">总弹幕数</div>
              <div class="output-stat-value">{{ totalDanmaku }}</div>
            </div>
            <div>
              <div class="output-stat-label">去重 ID 数</div>
              <div class="output-stat-value">{{ totalUsers }}</div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div v-if="revenueResults.length" class="output-section">
      <div class="output-section-title">最低收益预估</div>
      <div class="output-list">
        <div
          v-for="drama in revenueResults"
          :key="`revenue-${drama.dramaId}`"
          class="output-card"
        >
          <div class="output-card-title">
            {{ drama.subtitle || `${drama.title} / 单价 ${formatDiamond(drama.price)}` }}
          </div>
          <div class="output-stats">
            <div>
              <div class="output-stat-label">付费用户 ID 数</div>
              <div class="output-stat-value">
                {{ drama.failed ? "访问失败" : drama.paidUserCount }}
              </div>
            </div>
            <div>
              <div class="output-stat-label">
                {{ getRewardLabel(drama) }}
              </div>
              <div class="output-stat-value">
                {{
                  drama.failed
                    ? "访问失败"
                    : formatRewardValue(
                        drama.platform,
                        drama.platform === "manbo" ? drama.diamondValue : drama.rewardCoinTotal
                      )
                }}
              </div>
            </div>
            <div v-if="hasRewardNum(drama)">
              <div class="output-stat-label">打赏人数</div>
              <div class="output-stat-value">{{ formatPlainCountValue(drama.rewardNum) }}</div>
            </div>
          </div>
          <div class="output-revenue-line">
            <div class="output-stat-label">{{ getRevenueLabel(drama) }}</div>
            <div class="output-stat-value">
              {{
                drama.failed
                  ? "预估失败"
                  : shouldShowRevenueRange(drama)
                    ? formatRevenueRange(drama.minRevenueYuan, drama.maxRevenueYuan)
                    : formatRevenue(drama.estimatedRevenueYuan)
              }}
            </div>
          </div>
        </div>

        <div v-if="revenueSummary" class="output-summary-card">
          <div class="output-card-title">
            {{ revenueSummary.summaryTitle || `汇总 / 已选 ${revenueSummary.selectedDramaCount} 部` }}
          </div>
          <div class="output-stats">
            <div>
              <div class="output-stat-label">总和去重 ID</div>
              <div class="output-stat-value">
                {{ revenueSummary.failed ? "访问失败" : revenueSummary.totalPaidUserCount }}
              </div>
            </div>
            <div>
              <div class="output-stat-label">总播放量</div>
              <div class="output-stat-value">
                {{ revenueSummary.failed ? "访问失败" : formatPlayCountWanFixed(revenueSummary.totalViewCount) }}
              </div>
            </div>
            <div>
              <div class="output-stat-label">
                {{ getRewardLabel(revenueSummary, true) }}
              </div>
              <div class="output-stat-value">
                {{
                  revenueSummary.failed
                    ? "访问失败"
                    : formatRewardValue(revenueSummary.platform, revenueSummary.rewardTotal)
                }}
              </div>
            </div>
            <div v-if="hasRewardNum(revenueSummary)">
              <div class="output-stat-label">打赏人次</div>
              <div class="output-stat-value">{{ formatPlainCountValue(revenueSummary.rewardNum) }}</div>
            </div>
          </div>
          <div class="output-revenue-line">
            <div class="output-stat-label">收益预估</div>
            <div class="output-stat-value">
              {{
                revenueSummary.failed
                  ? "预估失败"
                  : shouldShowRevenueRange(revenueSummary)
                    ? formatRevenueRange(revenueSummary.minRevenueYuan, revenueSummary.maxRevenueYuan)
                    : formatRevenue(revenueSummary.estimatedRevenueYuan)
              }}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  emits: ["cancelStatistics"],
  props: {
    progress: Number,
    currentAction: String,
    elapsedMs: Number,
    playCountResults: Array,
    playCountSelectedEpisodeCount: Number,
    playCountTotal: Number,
    playCountFailed: Boolean,
    idResults: Array,
    idSelectedEpisodeCount: Number,
    totalDanmaku: Number,
    totalUsers: Number,
    revenueResults: Array,
    revenueSummary: Object,
    isRunning: Boolean,
  },
  methods: {
    getRewardLabel(drama, isSummary = false) {
      if (drama?.platform === "manbo") {
        return "投喂总数";
      }
      return isSummary ? "打赏榜总和" : "打赏榜累计";
    },
    formatRewardValue(platform, value) {
      const amount = Number(value ?? 0);
      return platform === "manbo" ? `${amount} 红豆` : `${amount} 钻石`;
    },
    hasRewardNum(drama) {
      return drama?.platform === "missevan"
        && drama?.rewardNum != null
        && Number.isFinite(Number(drama?.rewardNum));
    },
    formatPlainCountValue(value) {
      const count = Number(value ?? 0);
      if (!Number.isFinite(count)) {
        return "0";
      }
      return `${Math.trunc(count)}`;
    },
    shouldShowRevenueRange(drama) {
      if (!drama || drama.failed) {
        return false;
      }
      if (drama.minRevenueYuan == null || drama.maxRevenueYuan == null) {
        return false;
      }
      return Number.isFinite(Number(drama.minRevenueYuan))
        && Number.isFinite(Number(drama.maxRevenueYuan));
    },
    getRevenueLabel(drama) {
      return drama?.vipOnlyReward ? "预估收益（仅计算打赏）" : "预估收益";
    },
    formatPlayCountDisplay(value, failed) {
      if (failed) {
        return "部分分集统计失败";
      }
      const count = Number(value ?? 0);
      if (!Number.isFinite(count) || count <= 0) {
        return "0";
      }
      if (count < 10000) {
        return `${count}`;
      }
      if (count < 100000000) {
        return `${(count / 10000).toFixed(1)}万`;
      }
      return `${(count / 100000000).toFixed(2)}亿`;
    },
    formatPlayCountWanFixed(value) {
      const count = Number(value ?? 0);
      if (!Number.isFinite(count) || count <= 0) {
        return "0.0万";
      }
      return `${(count / 10000).toFixed(1)}万`;
    },
    formatDiamond(value) {
      return `${Number(value ?? 0)} 钻石`;
    },
    formatRevenue(value) {
      const amount = Number(value ?? 0);
      if (!Number.isFinite(amount) || amount <= 0) {
        return "0 元";
      }
      if (amount >= 100000000) {
        return `${(amount / 100000000).toFixed(2)} 亿元`;
      }
      if (amount >= 10000) {
        return `${(amount / 10000).toFixed(1)} 万元`;
      }
      if (Number.isInteger(amount)) {
        return `${amount} 元`;
      }
      return `${amount.toFixed(2).replace(/\.?0+$/, "")} 元`;
    },
    formatRevenueRange(minValue, maxValue) {
      return `${this.formatRevenue(minValue)} - ${this.formatRevenue(maxValue)}`;
    },
    formatElapsed(value) {
      const totalSeconds = Math.max(0, Math.floor(Number(value ?? 0) / 1000));
      const hours = Math.floor(totalSeconds / 3600);
      const minutes = Math.floor((totalSeconds % 3600) / 60);
      const seconds = totalSeconds % 60;

      if (hours > 0) {
        return `${hours}h ${String(minutes).padStart(2, "0")}m ${String(seconds).padStart(2, "0")}s`;
      }

      return `${minutes}m ${String(seconds).padStart(2, "0")}s`;
    },
  },
};
</script>

<style scoped>
.output-panel {
  display: grid;
  gap: 16px;
  padding: 18px;
}

.output-status-card,
.output-card,
.output-summary-card {
  padding: 16px;
  background: rgba(255, 255, 255, 0.82);
  border: 1px solid rgba(29, 53, 87, 0.08);
  border-radius: 18px;
}

.status-header {
  display: flex;
  gap: 12px;
  align-items: flex-start;
  justify-content: space-between;
}

.status-kicker {
  color: var(--text-muted);
  font-size: 12px;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

.status-text {
  margin-top: 6px;
  font-size: 18px;
  font-weight: 700;
  line-height: 1.4;
}

.status-elapsed {
  margin-top: 8px;
  color: var(--text-muted);
  font-size: 13px;
}

.status-side {
  display: inline-flex;
  flex-direction: column;
  align-items: flex-end;
  gap: 8px;
  text-align: right;
}

.status-badge {
  display: inline-flex;
  padding: 6px 10px;
  color: #fff;
  font-size: 12px;
  font-weight: 700;
  background: linear-gradient(135deg, #2f5d7c, #244962);
  border-radius: 999px;
}

.status-cancel-btn {
  min-height: 34px;
  padding: 6px 14px;
  color: #8a2d18;
  font-size: 13px;
  font-weight: 700;
  cursor: pointer;
  background: rgba(255, 241, 235, 0.9);
  border: 1px solid rgba(207, 92, 54, 0.2);
  border-radius: 999px;
}

.status-cancel-btn:hover {
  background: rgba(255, 233, 224, 0.96);
}

.status-progress {
  font-size: 20px;
  font-weight: 800;
}

.output-progress {
  height: 10px;
  margin-top: 16px;
  overflow: hidden;
  background: rgba(29, 53, 87, 0.08);
  border-radius: 999px;
}

.output-progress-bar {
  height: 100%;
  background: linear-gradient(135deg, var(--accent), var(--accent-strong));
  border-radius: inherit;
  transition: width 0.2s ease;
}

.output-section {
  display: grid;
  gap: 12px;
}

.output-section-title {
  font-size: 16px;
  font-weight: 800;
}

.output-list {
  display: grid;
  gap: 12px;
}

.output-card-title {
  font-size: 15px;
  font-weight: 800;
  line-height: 1.5;
}

.output-stats {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 12px;
  margin-top: 14px;
}

.output-stat-label {
  color: var(--text-muted);
  font-size: 12px;
  font-weight: 700;
}

.output-stat-value {
  margin-top: 6px;
  font-size: 18px;
  font-weight: 800;
  line-height: 1.3;
}

.output-revenue-line {
  margin-top: 14px;
  padding-top: 14px;
  border-top: 1px solid rgba(29, 53, 87, 0.08);
}

@media (max-width: 640px) {
  .output-panel {
    padding: 14px;
  }

  .status-header,
  .output-stats {
    grid-template-columns: 1fr;
  }

  .status-header {
    display: grid;
  }

  .status-side {
    display: grid;
    grid-template-columns: 1fr auto;
    align-items: center;
    text-align: left;
  }

  .status-badge {
    justify-self: start;
  }

  .status-cancel-btn {
    justify-self: end;
  }

  .status-progress {
    grid-column: 1 / -1;
    justify-self: start;
  }
}
</style>
